version: "3.9"

services:

  backend:
    build: backend/.
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  frontend:
    build: frontend/.
    ports:
      - "3500:3500"

  mongodb:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
