CREATE SCHEMA guesthouse;

CREATE TABLE guesthouse.HISTORIC (
    ID_HISTORIC SERIAL PRIMARY KEY,
    VERSION VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL
);

--

CREATE TABLE guesthouse.USERS (
    ID_USER SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    ID_ROLE INTEGER NOT NULL
);

--

CREATE TABLE guesthouse.ROLES (
    ID_ROLE INTEGER PRIMARY KEY,
    DESCRIPTION VARCHAR(100) NOT NULL
);

ALTER TABLE guesthouse.USERS
    ADD CONSTRAINT fk_id_role FOREIGN KEY (ID_ROLE) REFERENCES guesthouse.ROLES (ID_ROLE); 

--

CREATE TABLE guesthouse.GUESTS (
    ID_GUEST SERIAL PRIMARY KEY,
    NAME VARCHAR(100),
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    CPF VARCHAR(11) UNIQUE NOT NULL,
    PHONE_NUMBER VARCHAR(20),
    ID_ADDRESS INTEGER NOT NULL
);

--

CREATE TABLE guesthouse.ADDRESS(
    ID_ADDRESS SERIAL PRIMARY KEY,
    CEP VARCHAR(20),
    STATE VARCHAR(100),
    CITY VARCHAR(100),
    NEIGHBORHOOD VARCHAR(100),
    STREET VARCHAR(100),
    NUMBER VARCHAR(50)
);

ALTER TABLE guesthouse.GUESTS
    ADD CONSTRAINT fk_id_address FOREIGN KEY (ID_ADDRESS) REFERENCES guesthouse.ADDRESS (ID_ADDRESS) ;

--

CREATE TABLE guesthouse.PARKING (
    ID_PARKING SERIAL PRIMARY KEY,
    CHECKIN DATE,
    CHECKOUT DATE,
    CAR_TYPE VARCHAR(100)
);

--

CREATE TABLE guesthouse.RESERVATIONS (
    ID_RESERVATION SERIAL PRIMARY KEY,
    CHECKIN DATE NOT NULL,
    CHECKOUT DATE NOT NULL,
    ENTRY_VALUE DECIMAL(10,2) NOT NULL,
    PAID BOOLEAN DEFAULT FALSE NOT NULL,
    QUANT_GUESTS INTEGER NOT NULL,
    ROOM INTEGER NOT NULL,
    TOTAL_VALUE DECIMAL(10,2) NOT NULL,
    ID_GUEST INTEGER NOT NULL,
    ID_PARKING INTEGER,
    ID_USER INTEGER NOT NULL,
    ID_PAYMENT_TYPE INTEGER NOT NULL,
    ID_STATUS INTEGER NOT NULL,
    ID_TYPE_RESERVATION INTEGER NOT NULL
);

--

ALTER TABLE guesthouse.RESERVATIONS
    ADD CONSTRAINT fk_id_guest FOREIGN KEY (ID_GUEST) REFERENCES guesthouse.GUESTS (ID_GUEST);

ALTER TABLE guesthouse.RESERVATIONS
    ADD CONSTRAINT fk_id_parking FOREIGN KEY (ID_PARKING) REFERENCES guesthouse.PARKING (ID_PARKING);

ALTER TABLE guesthouse.RESERVATIONS
    ADD CONSTRAINT fk_id_user FOREIGN KEY (ID_USER) REFERENCES guesthouse.USERS (ID_USER);

--

CREATE TABLE guesthouse.PAYMENT_TYPE (
    ID_PAYMENT_TYPE SERIAL PRIMARY KEY,
    DESCRIPTION VARCHAR(30)
);

--

CREATE TABLE guesthouse.STATUS (
    ID_STATUS SERIAL PRIMARY KEY,
    DESCRIPTION VARCHAR(30)
);

--

CREATE TABLE guesthouse.TYPE_RESERVATION (
    ID_TYPE_RESERVATION SERIAL PRIMARY KEY,
    DESCRIPTION VARCHAR(30)
);

--

ALTER TABLE guesthouse.RESERVATIONS
    ADD CONSTRAINT fk_id_payment FOREIGN KEY (ID_PAYMENT_TYPE) REFERENCES guesthouse.PAYMENT_TYPE (ID_PAYMENT_TYPE);

ALTER TABLE guesthouse.RESERVATIONS
    ADD CONSTRAINT fk_id_status FOREIGN KEY (ID_STATUS) REFERENCES guesthouse.STATUS (ID_STATUS);

ALTER TABLE guesthouse.RESERVATIONS
    ADD CONSTRAINT fk_id_type_reservation FOREIGN KEY (ID_TYPE_RESERVATION) REFERENCES guesthouse.TYPE_RESERVATION (ID_TYPE_RESERVATION);