CREATE SCHEMA pousada;

CREATE TABLE HISTORIC (
    ID_HISTORIC SERIAL PRIMARY KEY,
    VERSION VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL
);

--

CREATE TABLE USERS (
    ID_USER SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    ID_ROLE INTEGER NOT NULL
);

--

CREATE TABLE ROLES (
    ID_ROLE INTEGER PRIMARY KEY,
    DESCRIPTION VARCHAR(100) NOT NULL
);

ALTER TABLE USERS
    ADD CONSTRAINT fk_id_role FOREIGN KEY (ID_ROLE) REFERENCES ROLES (ID_ROLE); 

--

CREATE TABLE GUESTS (
    ID_GUEST SERIAL PRIMARY KEY,
    NAME VARCHAR(100),
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    CPF VARCHAR(11) UNIQUE NOT NULL,
    PHONE_NUMBER VARCHAR(20),
    ID_ADDRESS INTEGER NOT NULL
);

--

CREATE TABLE ADDRESS(
    ID_ADDRESS SERIAL PRIMARY KEY,
    CEP VARCHAR(20),
    STATE VARCHAR(100),
    CITY VARCHAR(100),
    NEIGHBORHOOD VARCHAR(100),
    STREET VARCHAR(100),
    NUMBER VARCHAR(50)
);

ALTER TABLE GUESTS
    ADD CONSTRAINT fk_id_address FOREIGN KEY (ID_ADDRESS) REFERENCES ADDRESS (ID_ADDRESS) ;

--

CREATE TABLE PARKING (
    ID_PARKING SERIAL PRIMARY KEY,
    CHECKIN DATE,
    CHECKOUT DATE,
    CAR_TYPE VARCHAR(100)
);

--

CREATE TABLE RESERVATIONS (
    ID_RESERVATION SERIAL PRIMARY KEY,
    CHECKIN DATE NOT NULL,
    CHECKOUT DATE NOT NULL,
    ENTRY_VALUE DECIMAL(10,2) NOT NULL,
    PAID BOOLEAN DEFAULT FALSE NOT NULL,
    QUANT_GUESTS INTEGER NOT NULL,
    ROOM INTEGER NOT NULL,
    TOTAL_VALUE DECIMAL(10,2) NOT NULL,
    ID_GUEST INTEGER NOT NULL,
    ID_PARKING INTEGER,
    ID_USER INTEGER NOT NULL,
    ID_PAYMENT_TYPE INTEGER NOT NULL,
    ID_STATUS INTEGER NOT NULL,
    ID_TYPE_RESERVATION INTEGER NOT NULL
);

--

ALTER TABLE RESERVATIONS
    ADD CONSTRAINT fk_id_guest FOREIGN KEY (ID_GUEST) REFERENCES GUESTS (ID_GUEST);

ALTER TABLE RESERVATIONS
    ADD CONSTRAINT fk_id_parking FOREIGN KEY (ID_PARKING) REFERENCES PARKING (ID_PARKING);

ALTER TABLE RESERVATIONS
    ADD CONSTRAINT fk_id_user FOREIGN KEY (ID_USER) REFERENCES USERS (ID_USER);

--

CREATE TABLE PAYMENT_TYPE (
    ID_PAYMENT_TYPE SERIAL PRIMARY KEY,
    DESCRIPTION VARCHAR(30)
);

--

CREATE TABLE STATUS (
    ID_STATUS SERIAL PRIMARY KEY,
    DESCRIPTION VARCHAR(30)
);

--

CREATE TABLE TYPE_RESERVATION (
    ID_TYPE_RESERVATION SERIAL PRIMARY KEY,
    DESCRIPTION VARCHAR(30)
);

--

ALTER TABLE RESERVATIONS
    ADD CONSTRAINT fk_id_payment FOREIGN KEY (ID_PAYMENT_TYPE) REFERENCES PAYMENT_TYPE (ID_PAYMENT_TYPE);

ALTER TABLE RESERVATIONS
    ADD CONSTRAINT fk_id_status FOREIGN KEY (ID_STATUS) REFERENCES STATUS (ID_STATUS);

ALTER TABLE RESERVATIONS
    ADD CONSTRAINT fk_id_type_reservation FOREIGN KEY (ID_TYPE_RESERVATION) REFERENCES TYPE_RESERVATION (ID_TYPE_RESERVATION);