INSERT INTO ROLES (ID_ROLE, DESCRIPTION)
    VALUES (1, 'ROOT'), (2, 'ADMINISTRADOR'), (3, 'USUARIO');

INSERT INTO PAYMENT_TYPE (ID_PAYMENT_TYPE, DESCRIPTION)
VALUES (1, 'DINHEIRO'), (2, 'DÉBITO'), (3, 'CRÉDITO'), (4, 'PIX');

INSERT INTO TYPE_RESERVATION (ID_TYPE_RESERVATION, DESCRIPTION)
VALUES (1, 'TELEFONE'), (2, 'BOOKING'), (3, 'EXPEDIA'), (4, 'PRESENCIAL'), (5, 'AIRBNB'), (6, 'EMAIL');

INSERT INTO STATUS (ID_STATUS, DESCRIPTION)
VALUES (1, 'ATIVO'), (2, 'NAO_COMPARECEU'), (3, 'CANCELADO');
