spring.application.name=solriso-system

# DB
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.tlxzebrxqfbpegpxraah
spring.datasource.password=bqvgzVAU0v3VQa32
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração JPA/Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# JWT
jwt.secret=myPasswordForSystemOfReservation
jwt.expiration-in-minutes=15
jwt.issuer=reservation-system

